config/routes.rb
WirelessOrder::Application.routes.draw do
  resources :dish_styles

  resources :dish_types

  resources :menus

  resources :dishes do
    get 'select_type', on: :collection
    get 'select_style', on: :collection
    post 'image_upload', on: :collection
  end

  get 'authorities/index'

  root 'welcome#index'

  resources :welcome
  resources :authorities do
    get 'logout', on: :collection
  end
  resources :tables do
    get 'select_type', on: :collection
  end
  namespace :mobile do
    resources :login do
      post 'sign', on: :collection
    end

    resources :m_dish do
      get 'dish_type_list', on: :collection
      get 'dish_style_list', on: :collection
      get 'dish_type_list_on_sale', on: :collection
      get 'dish_type_list_recommend', on: :collection

    end

    resources :m_table do
      get 'dish_list', on: :collection
      get 'order', on: :collection
      get 'check_out', on: :collection
      get 'add_dish', on: :collection
      get 'remove_dish', on: :collection
      get 'verify_menu', on: :collection
    end
  end

end

app/models/menu.rb
# -*- encoding : utf-8 -*-
class Menu < ActiveRecord::Base
  belongs_to :table
  has_many :dish_menus, dependent: :destroy
  has_many :dishes, through: :dish_menus

  #Menu.status
  #0:未结账
  #1:已结转
  #2:已确认提交
end

app/controllers/menus_controller.rb
# -*- encoding : utf-8 -*-
class MenusController < ApplicationController

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/menus_helper.rb
# -*- encoding : utf-8 -*-
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>